repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: bash -c 'isort "$@" --profile black || true; git add -u' --
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
  
  - repo: local
    hooks:
        - id: mypy
          name: mypy
          entry: mypy project/
          language: system
          types: [python]
          pass_filenames: false
          verbose: true
  
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --cov=project tests/
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
        verbose: true
